import { Assistant } from 'next/font/google'
import './globals.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const assistant = Assistant({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={assistant.className}>{children}
        {/* <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js" defer /> */}
      </body>
    </html>
  )
}